# [Info]
site_name: 个人网站 # 左上角标题
site_url: https://michaelssman.github.io/
site_author: michael
site_description: michael的个人网站
# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: "" # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/michaelssman/michaelssman.github.io # 右上角点击跳转的链接
repo_name: michael.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 Michael # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://www.bilibili.com/
      name: Bilibili | michael # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/
      name: GitHub | michael
# [Navigtion]
nav:
  # - index.md
  - 多线程:
    - 多线程/多线程.md
    - 多线程/线程同步.md
    - 多线程/锁.md
    - 多线程/队列和函数.md
    - 多线程/GCD.md
    - 多线程/dispatch_queue_t.md
    - 多线程/swift多线程.md
  - iOS:
    - Swift:
      - iOS/Swift/数据类型.md 
      - iOS/Swift/类与结构体.md
      - iOS/Swift/属性.md
      - iOS/Swift/defer.md
      - iOS/Swift/泛型和关联类型.md
      - iOS/Swift/闭包.md
      - iOS/Swift/as.md
      - iOS/Swift/源码.md
      - iOS/Swift/集合类.md
      - iOS/Swift/运算符重载.md
      - iOS/Swift/高阶函数.md
      - iOS/Swift/访问权限.md
      - iOS/Swift/Optional.md
      - iOS/Swift/方法调度.md
      - iOS/Swift/条件控制.md
      - iOS/Swift/Mirror_throws_Error.md
      - iOS/Swift/Moya.md
      - iOS/Swift/OC和Swift混编.md
      - iOS/Swift/协议.md
      - iOS/Swift/指针和内存管理.md
      - iOS/Swift/enum.md
      - iOS/Swift/IR.md
      - iOS/Swift/错误处理.md
    - 底层原理分析:
      - iOS/底层原理分析/底层探索分析.md
      - iOS/底层原理分析/LLDB指令.md
    - 01对象原理:
      - iOS/01对象原理/alloc.md
      - iOS/01对象原理/isa.md
      - iOS/01对象原理/对象原理.md
      - iOS/01对象原理/内存对齐.md
      - iOS/01对象原理/联合体和位域.md
    - 02类的原理:
      - iOS/02类的原理/类的原理.md
      - iOS/02类的原理/内存平移.md
      - iOS/02类的原理/cache.md
      - iOS/02类的原理/isKind和isMember.md
    - iOS/block.md
    - 03Runtime:
      - iOS/03Runtime/category.md
      - iOS/03Runtime/runtime.md
      - iOS/03Runtime/消息机制.md
      - iOS/03Runtime/Aspect.md
    - 04应用程序加载:
      - MachO: iOS/04应用程序加载/MachO.md
      - clang插件: iOS/04应用程序加载/clang插件.md
      - fishhook: iOS/04应用程序加载/fishhook.md
      - iOS应用加载流程: iOS/04应用程序加载/iOS应用加载流程.md
      - iOS/04应用程序加载/编译流程.md
      - 应用启动优化: iOS/04应用程序加载/应用启动优化.md
      - 环境变量: iOS/04应用程序加载/环境变量.md
      - 符号表: iOS/04应用程序加载/符号表.md
      - 动态库静态库:
        - iOS/04应用程序加载/动态库静态库/动态库静态库.md
        - iOS/04应用程序加载/动态库静态库/swift的module.md
      - iOS/04应用程序加载/hmap.md
      - iOS/04应用程序加载/多环境支持.md
    - 内存管理:
      - iOS/内存管理/copy.md
      - iOS/内存管理/iOS属性关键字.md
      - iOS/内存管理/weak原理.md
      - iOS/内存管理/内存管理.md
    - 06Runloop:
      - iOS/06Runloop/00RunLoop.md
      - iOS/06Runloop/01CFRunLoopRef.md
      - iOS/06Runloop/02CFRunLoopModeRef.md
      - iOS/06Runloop/03CFRunLoopSourceRef.md
      - iOS/06Runloop/04CFRunLoopTimerRef.md
      - iOS/06Runloop/05CFRunLoopObserverRef.md
      - iOS/06Runloop/线程保活.md
      - iOS/06Runloop/自动释放池.md
    - 08组件化:
      - iOS/08组件化/CocoaPods原理.md
      - iOS/08组件化/Pod.md
      - iOS/08组件化/组件化.md
      - iOS/08组件化/组件化通讯.md
    - iOS/响应者链.md
    - 10性能优化:
      - iOS/10性能优化/内存检测.md
      - iOS/10性能优化/界面优化.md
    - 11架构模式:
      - iOS/11架构模式/MVX.md
    - 13crash分析:
      - iOS/13crach分析/crash分析.md
      - iOS/13crach分析/处理bug.md
    - iOS/KVO.md
    - iOS/KVC.md
    - iOS/Animation.md
    - NSArray:
      - iOS/NSArray/数组随机10条数据.md
      - iOS/NSArray/遍历数组.md
    - SDWebImage:
      - iOS/SDWebImage/SDImageCache.md
      - iOS/SDWebImage/SDWebImage.md
      - iOS/SDWebImage/SDWebImageManager.md
    - WKWebView:
      - iOS/WKWebView/WKWebView.md
      - iOS/WKWebView/WKWebView聚焦.md
      - iOS/WKWebView/解决webView白屏问题加载缓存问题.md
    - 推送:
      - iOS/推送/极光推送.md
      - iOS/推送/角标问题.md
      - iOS/推送/推送开关功能.md
    - 编程思想:
      - iOS/编程思想/编程思想.md
      - iOS/编程思想/函数式/funtional_programming.md
      - iOS/编程思想/响应式/响应式编程.md
      - iOS/编程思想/响应式/RAC/01RACSignal.md
      - iOS/编程思想/响应式/RAC/02RACSubject和RACReplaySubject.md
      - iOS/编程思想/响应式/RAC/RACCommand.md
      - iOS/编程思想/响应式/RAC/RACDisposable.md
      - iOS/编程思想/响应式/RAC/RACMulticastConnection.md
      - iOS/编程思想/响应式/RAC/RAC基本用法.md
      - iOS/编程思想/响应式/RAC/RAC过滤.md
    - iOS/数据持久化/CoreData.md
    - iOS/PDF文件查看.md
    - iOS/Vendors.md
    - iOS/universalLink.md
    - iOS/快捷键.md
    - iOS/控制器生命周期.md
    - iOS/版本更新.md
    - iOS/数据精确度.md
  - 音视频:
    - 图像:
      - 音视频/图像/专业名词解释.md
      - 音视频/图像/图像显示原理.md
      - 音视频/图像/图片加载解码渲染.md
    - 音视频/视频基本知识.md
    - 音视频/AVFoundation.md
    - 音视频/H264.md
    - 音视频/视频编解码.md
    - 音视频/音频.md
    - 音视频/倒放视频.md
  - C++: 
    - README: C++/README.md
    - C++/字符串和头文件.md
    - C++/文件的读写和容器.md
    - C++/名称空间和作用域.md
    - C++/运算符重载.md
    - C++/迭代器.md 
    - C++/内联函数.md
    - C++/构造函数和析构函数.md
    - C++/继承和组合.md
    - C++/引用和指针.md
    - C++/替代链接.md
    - C++/默认参数和函数重载.md
    - C++/内存分配和释放.md
    - vscode运行C: C++/vscode运行C++.md
    - 函数和函数库: C++/函数和函数库.md
    - 动态创建对象: C++/动态创建对象.md
    - 友元: C++/友元.md
    - 句柄类: C++/句柄类.md
    - C++/库.md
    - 打开和关闭所有权: C++/打开和关闭所有权.md
    - 拷贝构造函数: C++/拷贝构造函数.md
    - 控制链接: C++/控制链接.md
    - 改进的错误检查方法: C++/改进的错误检查方法.md
    - 类和结构体: C++/类和结构体.md
    - 联合: C++/联合.md
    - 自动类型转换: C++/自动类型转换.md
    - 访问函数: C++/访问函数.md
    - 访问控制: C++/访问控制.md
    - 多态性和虚函数:
      - C++/多态性和虚函数/01多态性和虚函数.md
      - C++/多态性和虚函数/02多态性和虚函数.md
      - C++/多态性和虚函数/03多态性和虚函数.md
      - C++/多态性和虚函数/04多态性和虚函数.md
      - C++/多态性和虚函数/05多态性和虚函数.md
    - 模版:
      - C++/模版/模版template.md
      - C++/模版/Stack模板.md
      - C++/模版/模版化的指针Stash.md
  - flutter:
    - dart:
      - flutter/Dart/dart.md
      - flutter/Dart/数据类型.md
      - flutter/Dart/运算符重载.md
      - flutter/Dart/类和对象.md
      - flutter/Dart/abstract.md
      - flutter/Dart/factory和单例.md
      - flutter/Dart/Mixin多继承.md
      - flutter/Dart/方法.md
    - flutter/flutter简介.md
    - flutter/flutter安装.md
    - flutter/AS快捷键.md
    - flutter/pubspec.yaml文件管理.md
    - flutter/本地资源和工程配置.md
    - flutter/生命周期.md
    - flutter/状态管理.md
    - flutter/Key的原理.md
    - flutter/json和map转model.md
    - flutter/手势.md
    - flutter/package和plugin.md
    - flutter/Provider.md
    - flutter/widget.md
    - flutter/widget/PageView.md
    - flutter/widget/TabBarView.md
    - flutter/widget/TextField.md
    - flutter/widget/showModelBottomSheet.md
    - flutter/布局.md
    - flutter/混合开发与引擎.md
    - flutter/渲染原理.md
    - flutter/热重载.md
    - flutter/网络.md
    - 异步和多线程:
      - flutter/异步和多线程/异步Future.md
      - flutter/异步和多线程/异步和多线程.md
  - 数据结构与算法:
    - 数据结构:
      - 数据结构与算法/数据结构/数据结构.md
      - 数据结构与算法/数据结构/数组.md
      - 01链表:
        - 数据结构与算法/数据结构/01链表/00线性表.md
        - 数据结构与算法/数据结构/01链表/01链表的基本概念.md
        - 数据结构与算法/数据结构/01链表/02模版类实现链表.md
        - 数据结构与算法/数据结构/01链表/03链表迭代器.md
        - 数据结构与算法/数据结构/01链表/04循环链表.md
        - 数据结构与算法/数据结构/01链表/05双向链表.md
        - 数据结构与算法/数据结构/01链表/06顺序容器.md
      - 02栈:
        - 数据结构与算法/数据结构/02栈/000栈Stack.md
        - 数据结构与算法/数据结构/02栈/03栈Stack.md
      - 03队列:
        - 数据结构与算法/数据结构/03队列/队列.md
      - 04树:
        - 数据结构与算法/数据结构/04树/树.md
        - 数据结构与算法/数据结构/04树/01树.md
        - 数据结构与算法/数据结构/04树/02二叉树.md
        - 数据结构与算法/数据结构/04树/红黑树.md
        - 数据结构与算法/数据结构/04树/B树.md
      - 05堆:
        - 数据结构与算法/数据结构/05堆/01堆.md
      - 06图:
        - 数据结构与算法/数据结构/06图/图.md
      - 07哈希和映射:
        - 数据结构与算法/数据结构/07哈希和映射/哈希和映射.md
    - 算法:
      - 数据结构与算法/算法/README.md
      - 数据结构与算法/算法/00排序.md
      - 数据结构与算法/算法/交换swap.md
      - 数据结构与算法/算法/排序算法.md
      - 数据结构与算法/算法/加密.md
      - 数据结构与算法/算法/基数排序.md
      - 数据结构与算法/算法/归并排序merge.md
      - 数据结构与算法/算法/快速排序quicksort.md
      - 数据结构与算法/算法/排列组合Perm.md
      - 数据结构与算法/算法/查找算法.md
      - 数据结构与算法/算法/递归.md
      - 数据结构与算法/算法/面试.md
      - 数据结构与算法/算法/面试/删除倒数第n个节点.md
      - 数据结构与算法/算法/面试/数组n个数组合最大的数.md
      - 数据结构与算法/算法/面试/玻璃球.md
      - 数据结构与算法/算法/面试/第几瓶水有毒.md
      - 数据结构与算法/算法/面试/阿里.md
  - 计算机网络:
    - 计算机网络/网络模型.md
    - 计算机网络/TCP_IP协议.md
    - 计算机网络/TCP和UDP.md
    - 计算机网络/URI.md
    - 计算机网络/Http.md
    - 计算机网络/基础概念.md
    - 计算机网络/DNS.md
    - 计算机网络/Cookie.md
    - 计算机网络/Socket.md
    - 计算机网络/XMPP.md
    - 计算机网络/RTP.md
  - 版本控制:
    - 版本控制/git.md
    - 版本控制/git_config.md
    - 版本控制/git_ignore.md
    - 版本控制/svn.md
  - 设计模式:
    - 设计模式/README.md
    - 设计模式/结构模式.md
    - 设计模式/设计模式基本原则.md
    - 创建型模式:
      - 设计模式/创建型模式/01单例模式.md
      - 设计模式/创建型模式/02工厂模式.md
      - 设计模式/创建型模式/03建造者模式.md
      - 设计模式/创建型模式/04创建者模式和工厂模式的区别.md
      - 设计模式/创建型模式/05原型模式Prototype.md
    - 结构型模式:
      - 设计模式/结构型模式/06代理模式Proxy.md
      - 设计模式/结构型模式/07装饰模式Decorator Pattern.md
      - 设计模式/结构型模式/08适配器模式 Adapter.md
      - 设计模式/结构型模式/09组合模式Composite.md
      - 设计模式/结构型模式/10桥接模式Bridge.md
      - 设计模式/结构型模式/11外观模式Facade.md
      - 设计模式/结构型模式/12享元模式Flyweight.md
    - 行为型模式:
      - 设计模式/行为型模式/13模版模式Template.md
      - 设计模式/行为型模式/14命令模式Command.md
      - 设计模式/行为型模式/15责任链模式.md
      - 设计模式/行为型模式/16策略模式Strategy.md
      - 设计模式/行为型模式/17中介者模式Mediator.md
      - 设计模式/行为型模式/18观察者模式Observer.md
      - 设计模式/行为型模式/19备忘录模式Memento.md
      - 设计模式/行为型模式/20访问者模式Visitor.md
      - 设计模式/行为型模式/21状态模式State.md
      - 设计模式/行为型模式/22解释模式Interpreter.md
      - 设计模式/行为型模式/23迭代器模式Iterator.md
      - 设计模式/行为型模式/总结.md
  - Html:
    - css: Html/CSS/css.md
    - html: Html/Html/html.md
    - JavaScript:
      - Html/JavaScript/JavaScript简介.md
      - Html/JavaScript/变量.md
      - Html/JavaScript/数据类型.md
    - vue:
      - Html/Vue/Vue.md
      - Html/Vue/vue框架.md
      - Html/Vue/数据.md
      - Html/Vue/文件路径.md
      - Html/Vue/模版方法.md
      - Html/Vue/添加实例 property.md
  - static_const_define: 
    - 宏: 常量_宏_静态变量/宏定义和常量.md
    - 常量_宏_静态变量/static.md
    - 常量: 
      - 常量_宏_静态变量/const.md
      - 常量_宏_静态变量/04常量.md
      - 常量_宏_静态变量/05常量.md
      - 常量_宏_静态变量/06常量.md
  - 数据库:
    - 数据库/数据库.md
  - 正则:
    - 正则/正则表达式.md
  - 计算机基础: 
      - 计算机基础/位运算.md
      - 计算机基础/查看源码.md
  - Mac:
    - MAC/brew.md
    - MAC/linux.md
    - MAC/hosts.md
    - MAC/Mac快捷键.md
    - MAC/搭建网站.md
    - MAC/清理Xcode.md
    - MAC/软件.md
    - MAC/vscode.md

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > mkjavascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > mkjavascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols