# [Info]
site_name: 个人网站 # 左上角标题
site_url: https://michaelssman.github.io/
site_author: michael
site_description: michael的个人网站
# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: "" # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/michaelssman/michaelssman.github.io # 右上角点击跳转的链接
repo_name: michael.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2024 Michael # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://www.bilibili.com/
      name: Bilibili | michael # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/
      name: GitHub | michael
# [Navigtion]
nav:
  # - index.md
  - iOS:
    - Swift:
      - iOS/Swift/数据类型.md 
      - iOS/Swift/类与结构体.md
      - iOS/Swift/属性.md
      - iOS/Swift/defer.md
      - iOS/Swift/泛型和关联类型.md
      - iOS/Swift/闭包.md
      - iOS/Swift/as.md
      - iOS/Swift/源码.md
      - iOS/Swift/运算符重载.md
      - iOS/Swift/高阶函数.md
      - iOS/Swift/Optional.md
      - iOS/Swift/流程控制.md
      - iOS/Swift/Mirror_throws_Error.md
      - iOS/Swift/Moya.md
      - iOS/Swift/OC和Swift混编.md
      - iOS/Swift/协议.md
      - iOS/Swift/指针和内存管理.md
      - iOS/Swift/enum.md
      - iOS/Swift/IR.md
    - 底层原理分析:
      - iOS/底层原理分析/底层探索分析.md
      - iOS/底层原理分析/LLDB指令.md
    - 对象原理:
      - iOS/对象原理/alloc.md
      - iOS/对象原理/isa.md
      - iOS/对象原理/对象原理.md
      - iOS/对象原理/内存对齐.md
    - 类的原理:
      - iOS/类的原理/类的原理.md
      - iOS/类的原理/内存平移.md
      - iOS/类的原理/cache.md
      - iOS/类的原理/isKind和isMember.md
    - iOS/block.md
    - Runtime:
      - iOS/Runtime/category.md
      - iOS/Runtime/runtime.md
      - iOS/Runtime/消息机制.md
      - iOS/Runtime/Aspect.md
    - 应用程序加载:
      - iOS/应用程序加载/MachO.md
      - iOS/应用程序加载/fishhook.md
      - iOS应用加载流程: iOS/应用程序加载/iOS应用加载流程.md
      - 应用启动优化: iOS/应用程序加载/应用启动优化.md
      - 符号表: iOS/应用程序加载/符号表.md
      - iOS/应用程序加载/hmap.md
      - iOS/应用程序加载/动态库静态库.md
      - iOS/应用程序加载/多环境支持.md
    - Runloop:
      - iOS/Runloop/00RunLoop.md
      - iOS/Runloop/01CFRunLoopRef.md
      - iOS/Runloop/02CFRunLoopModeRef.md
      - iOS/Runloop/03CFRunLoopSourceRef.md
      - iOS/Runloop/04CFRunLoopTimerRef.md
      - iOS/Runloop/05CFRunLoopObserverRef.md
      - iOS/Runloop/线程保活.md
      - iOS/Runloop/自动释放池.md
    - 组件化:
      - iOS/组件化/CocoaPods原理.md
      - iOS/组件化/Pod.md
      - iOS/组件化/组件化.md
      - iOS/组件化/组件化通讯.md
    - iOS/响应者链.md
    - 性能优化:
      - iOS/性能优化/内存检测.md
      - iOS/性能优化/界面优化.md
    - crash分析:
      - iOS/crach分析/crash分析.md
      - iOS/crach分析/处理bug.md
    - iOS/KVO.md
    - iOS/KVC.md
    - iOS/Animation.md
    - SDWebImage:
      - iOS/SDWebImage/SDImageCache.md
      - iOS/SDWebImage/SDWebImage.md
      - iOS/SDWebImage/SDWebImageManager.md
    - iOS/WKWebView.md
    - 架构模式和编程思想:
      - iOS/架构模式和编程思想/架构模式/MVX.md
      - iOS/架构模式和编程思想/编程思想/编程思想.md
      - iOS/架构模式和编程思想/编程思想/函数式/funtional_programming.md
      - iOS/架构模式和编程思想/编程思想/响应式/响应式编程.md
      - iOS/架构模式和编程思想/编程思想/响应式/RAC/RACSignal.md
      - iOS/架构模式和编程思想/编程思想/响应式/RAC/02RACSubject和RACReplaySubject.md
      - iOS/架构模式和编程思想/编程思想/响应式/RAC/RACCommand.md
      - iOS/架构模式和编程思想/编程思想/响应式/RAC/RACDisposable.md
      - iOS/架构模式和编程思想/编程思想/响应式/RAC/RACMulticastConnection.md
      - iOS/架构模式和编程思想/编程思想/响应式/RAC/RAC基本用法.md
      - iOS/架构模式和编程思想/编程思想/响应式/RAC/takeUntil过滤.md
      - iOS/架构模式和编程思想/编程思想/响应式/RXSwift/RXSwift.md
      - iOS/架构模式和编程思想/编程思想/响应式/RXSwift/UI.md
      - iOS/架构模式和编程思想/编程思想/响应式/数据同步更新.md
    - iOS/数据持久化/CoreData.md
    - iOS/universalLink.md
    - iOS/快捷键.md
    - iOS/控制器生命周期.md
    - iOS/版本更新.md
    - iOS/数据精确度.md
  - 音视频:
    - 图像:
      - 音视频/图像/专业名词解释.md
      - 音视频/图像/图像显示原理.md
      - 音视频/图像/图片加载解码渲染.md
      - 音视频/图像/图片格式算法.md
    - 音视频/视频基本知识.md
    - 音视频/AVFoundation.md
    - 音视频/H264.md
    - 音视频/视频编解码.md
    - 音视频/音频.md
    - 音视频/倒放视频.md
    - 音视频/超帧.md
  - 操作系统:
    - 内存管理:
      - 操作系统/内存管理/copy.md
      - 操作系统/内存管理/iOS属性关键字.md
      - 操作系统/内存管理/weak原理.md
      - 操作系统/内存管理/内存管理.md
    - 多线程:
      - 操作系统/多线程/GCD.md
      - 操作系统/多线程/swift多线程.md
      - 操作系统/多线程/多线程.md
      - 操作系统/多线程/线程同步.md
      - 操作系统/多线程/锁.md
      - 操作系统/多线程/队列和函数.md
      - 操作系统/多线程/Java/Java多线程.md
    - 操作系统/IO.md
    - 操作系统/运算符.md
    - 操作系统/数据处理.md
    - 操作系统/正则.md
    - 操作系统/缓存.md
    - 操作系统/联合体和位域.md
  - 编程:
    - const_macro_static:
      - 编程/const_macro_static/04常量.md
      - 编程/const_macro_static/05常量.md
      - 编程/const_macro_static/const.md
      - 编程/const_macro_static/static.md
      - 编程/const_macro_static/宏定义和常量.md
    - 异常处理:
      - 编程/异常处理/C++.md
      - 编程/异常处理/Java.md
      - 编程/异常处理/swift.md
    - 编程/Enum&OPTIONS.md
    - 编程/XML.md
    - 编程/token.md
    - 编程/typedef.md
    - 编程/方法调度.md
    - 编程/注解.md
    - 编程/继承多态接口.md
    - 编程/编译流程.md
    - 模块和访问权限:
      - 编程/模块&访问权限/访问权限.md
      - 编程/模块&访问权限/模块.md
  - C++: 
    - C++/README.md
    - C++/字符串和头文件.md
    - C++/文件的读写和容器.md
    - C++/名称空间和作用域.md
    - C++/运算符重载.md
    - C++/迭代器.md 
    - C++/内联函数.md
    - C++/构造函数和析构函数.md
    - C++/继承和组合.md
    - C++/引用和指针.md
    - C++/替代链接.md
    - C++/默认参数和函数重载.md
    - C++/内存分配和释放.md
    - C++/vscode运行C++.md
    - C++/函数和函数库.md
    - C++/动态创建对象.md
    - C++/句柄类.md
    - C++/打开和关闭所有权.md
    - C++/拷贝构造函数.md
    - C++/链接.md
    - C++/自动类型转换.md
    - 访问函数: C++/面向对象.md
    - C++/访问控制.md
    - 多态和虚函数:
      - C++/多态和虚函数/虚函数.md
      - C++/多态和虚函数/多态和虚函数.md
    - C++/模版template.md
  - flutter:
    - dart:
      - flutter/Dart/dart.md
      - flutter/Dart/数据类型.md
      - flutter/Dart/运算符重载.md
      - flutter/Dart/类对象抽象类.md
      - flutter/Dart/factory和单例.md
      - flutter/Dart/Mixin多继承.md
      - flutter/Dart/方法.md
    - flutter/flutter简介.md
    - flutter/AS快捷键.md
    - flutter/pubspec.yaml.md
    - flutter/本地资源和工程配置.md
    - flutter/生命周期.md
    - flutter/状态管理.md
    - flutter/Key.md
    - flutter/json和map转model.md
    - flutter/手势.md
    - flutter/package和plugin.md
    - flutter/绘画.md
    - widget:
      - flutter/widget/widget.md
      - flutter/widget/Material.md
      - flutter/widget/MaterialApp.md
      - flutter/widget/状态栏.md
      - flutter/widget/Scaffold.md
      - flutter/widget/PageView.md
      - flutter/widget/TabBar和TabBarView.md
      - flutter/widget/滚动.md
      - flutter/widget/TextField.md
      - flutter/widget/showModelBottomSheet.md
      - flutter/widget/Sliver.md
      - flutter/widget/Widgets.md
      - flutter/widget/Text.md
      - flutter/widget/带组头列表.md
      - flutter/widget/筛选页面.md
    - flutter/布局.md
    - flutter/数据持久化.md
    - flutter/拷贝.md
    - flutter/混合开发与引擎.md
    - flutter/渲染原理.md
    - flutter/热重载.md
    - flutter/网络.md
    - flutter/动画.md
    - flutter/Navigator.md
    - flutter/widget/NotificationListener.md
    - flutter/app密码保护.md
    - 异步和多线程:
      - flutter/异步和多线程/异步Future.md
      - flutter/异步和多线程/异步和多线程.md
      - flutter/异步和多线程/async和await.md
  - 数据结构与算法:
    - 数据结构:
      - 数据结构与算法/数据结构/数据结构.md
      - 数据结构与算法/数据结构/数组.md
      - 链表:
        - 数据结构与算法/数据结构/链表/线性表.md
        - 数据结构与算法/数据结构/链表/链表.md
        - 数据结构与算法/数据结构/链表/STL中的list.md
      - 数据结构与算法/数据结构/栈Stack.md
      - 数据结构与算法/数据结构/队列.md
      - 树:
        - 数据结构与算法/数据结构/树/树.md
        - 数据结构与算法/数据结构/树/红黑树.md
        - 数据结构与算法/数据结构/树/B树.md
      - 数据结构与算法/数据结构/堆.md
      - 数据结构与算法/数据结构/图.md
      - 数据结构与算法/数据结构/哈希和映射.md
    - 算法:
      - 数据结构与算法/算法/README.md
      - 数据结构与算法/算法/交换swap.md
      - 数据结构与算法/算法/排序算法.md
      - 数据结构与算法/算法/加密.md
      - 数据结构与算法/算法/基数排序.md
      - 数据结构与算法/算法/快速排序quicksort.md
      - 数据结构与算法/算法/排列组合Perm.md
      - 数据结构与算法/算法/查找算法.md
      - 数据结构与算法/算法/递归.md
      - 数据结构与算法/算法/面试/删除倒数第n个节点.md
      - 数据结构与算法/算法/面试/数组n个数组合最大的数.md
      - 数据结构与算法/算法/面试/玻璃球.md
      - 数据结构与算法/算法/面试/阿里.md
      - 数据结构与算法/算法/哈希集合.md
      - 数据结构与算法/算法/Map.md
  - 计算机网络:
    - 计算机网络/网络模型.md
    - 计算机网络/网络协议.md
    - 计算机网络/TCP和UDP.md
    - 计算机网络/Http.md
    - 计算机网络/基础概念.md
    - 计算机网络/URI和DNS.md
    - 计算机网络/Cookie.md
    - 计算机网络/Socket.md
    - 计算机网络/XMPP.md
    - 计算机网络/RTP.md
    - 计算机网络/SSH.md
  - 版本控制:
    - 版本控制/git.md
    - 版本控制/git_config.md
    - 版本控制/git_ignore.md
  - 设计模式:
    - 设计模式/README.md
    - 创建型模式:
      - 设计模式/创建型模式/单例模式.md
      - 设计模式/创建型模式/工厂模式.md
      - 设计模式/创建型模式/03建造者模式.md
      - 设计模式/创建型模式/04创建者模式和工厂模式的区别.md
      - 设计模式/创建型模式/05原型模式Prototype.md
    - 结构型模式:
      - 设计模式/结构型模式/代理模式Proxy.md
      - 设计模式/结构型模式/07装饰模式Decorator Pattern.md
      - 设计模式/结构型模式/08适配器模式 Adapter.md
      - 设计模式/结构型模式/09组合模式Composite.md
      - 设计模式/结构型模式/10桥接模式Bridge.md
      - 设计模式/结构型模式/11外观模式Facade.md
      - 设计模式/结构型模式/12享元模式Flyweight.md
    - 行为型模式:
      - 设计模式/行为型模式/13模版模式Template.md
      - 设计模式/行为型模式/14命令模式Command.md
      - 设计模式/行为型模式/15责任链模式.md
      - 设计模式/行为型模式/16策略模式Strategy.md
      - 设计模式/行为型模式/17中介者模式Mediator.md
      - 设计模式/行为型模式/18观察者模式Observer.md
      - 设计模式/行为型模式/19备忘录模式Memento.md
      - 设计模式/行为型模式/20访问者模式Visitor.md
      - 设计模式/行为型模式/21状态模式State.md
      - 设计模式/行为型模式/22解释模式Interpreter.md
      - 设计模式/行为型模式/23迭代器模式Iterator.md
      - 设计模式/行为型模式/总结.md
  - Html:
    - css: Html/CSS/css.md
    - html: Html/Html/html.md
    - JavaScript:
      - Html/JavaScript/JavaScript简介.md
      - Html/JavaScript/变量.md
      - Html/JavaScript/数据类型.md
    - vue:
      - Html/Vue/Vue.md
      - Html/Vue/vue框架.md
      - Html/Vue/数据.md
      - Html/Vue/文件路径.md
      - Html/Vue/模版方法.md
      - Html/Vue/添加实例 property.md
  - Java:
    - Java/Java.md
    - Java/数据类型.md
    - Java/实体类.md
    - Java/IO.md
    - Java/JDBC.md
    - Maven:
      - Java/Maven/Maven.md
      - Java/Maven/pom.xml.md
    - Java/框架.md
    - Java分层:
      - Java/Java分层/Controller控制层.md
      - Java/Java分层/Java分层.md
      - Java/Java分层/Mapper数据库连接层.md
      - Java/Java分层/Service业务层.md
    - Java/日志功能.md
    - Java/目录结构.md
    - Java/MyBatis.md
    - Java/Spring.md
    - Java/SpringMVC&SSM.md
    - Java/SpringBoot.md
    - Java/JWT.md
  - HarmonyOS:
    - Harmony/数据类型.md
    - Harmony/class.md
    - Harmony/啊啊啊.md
    - Harmony/声明式UI.md
    - Harmony/lazyForEach.md
  - 数据库:
    - 数据库/SQL.md
    - 数据库/MySQL.md
    - 数据库/设计表.md
    - 数据库/事务.md
  - Mac:
    - MAC/软件包管理系统.md
    - MAC/linux.md
    - MAC/hosts.md
    - MAC/Mac快捷键.md
    - MAC/搭建网站.md
    - MAC/清理Xcode.md
    - MAC/software.md
    - MAC/vscode.md
  - app:
    - app/jizhanghelp.md
    - app/jizhangpp.md
    - app/jizhangversion.md

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > mkjavascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > mkjavascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols